services:
  airflow-postgres:
    image: postgres
    environment:
      - POSTGRES_USER=airflow       # PostgreSQL 用戶名
      - POSTGRES_PASSWORD=airflow   # PostgreSQL 密碼
      - POSTGRES_DB=airflow         # 創建的 PostgreSQL 數據庫名稱
    ports:
      - "5432:5432"
    networks:
      - mlflow_server_default
  airflow-init:
    image: apache/airflow:2.3.0
    depends_on:
      - airflow-postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
    command: 
      bash -c "airflow db init
      && airflow db upgrade
      && sleep 10"   
    networks:
      - mlflow_server_default
  create-admin:
    image: apache/airflow:2.3.0
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
    command:
      - bash
      - -c
      - |
        airflow users create \
          --username admin \
          --password admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com
    networks:
      - mlflow_server_default
  webserver:
    image: apache/airflow:2.3.0
    tty: true
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor                          # 使用本地執行器
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow     # Airflow 連接 PostgreSQL 的 URL
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow.cfg:/opt/airflow/airflow.cfg
    networks:
      - mlflow_server_default
  scheduler:
    image: apache/airflow:2.3.0
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor                         # 使用本地執行器
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow    # Airflow 連接 PostgreSQL 的 URL
    depends_on:
      - airflow-init
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - mlflow_server_default
networks:
  mlflow_server_default:
    external: true