version: '3'
services:
    training-endpoint:
        build: . 
        ports:
            - 9999:9999
        expose:
            - 9999
        networks:
            - mlflow_server_default
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
networks:
    mlflow_server_default:
        external: true
