services:
    training-database:
        image: ddmal/postgres-plpython:nightly
        environment:
            POSTGRES_USER: mlops
            POSTGRES_PASSWORD: mlops
            POSTGRES_DB: imdb_db
        expose:
            - 5432
        ports: 
            - 2345:5432
        networks:
            - 04_model_tracking_and_monitoring_default
        volumes:
            - ./build_trigger.sql:/docker-entrypoint-initdb.d/init.sql

networks:
    04_model_tracking_and_monitoring_default:
        external: true
    