services:
    training-database:
        image: ddmal/postgres-plpython:nightly
        environment:
            POSTGRES_USER: mlops
            POSTGRES_PASSWORD: mlops
            POSTGRES_DB: imdb_db
        expose:
            - 5432
        ports: 
            - 2345:5432
        networks:
            - mlops_network
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
    mlops_network:
        external: true
    